import org.junit.Test

import org.junit.Assert.*

class WallServiceTest {
    var service = WallService

    @Test
    fun addFunction() {
            val post = Post(postId = 1)
            val postIdExpected = 3
            service.add(post)
            val result = service.add(post).postId
            assertEquals(postIdExpected, result)
        }

        @Test
        fun updateExisting_True() {
            service.add(Post( 3,
                3,
                1,
                1,
                1,
                "Текст поста!",
                2,
                1,
                true,
                comment,
                copyright,
                likes,
                reports,
                views,
                POST,
                1,
                false,
                false,
                false,
                true,
                false,
                true,
                donut,
                1))
            service.add(Post( 2,
                5,
                2,
                1,
                3,
                "Текст поста!",
                2,
                1,
                true,
                comment,
                copyright,
                likes,
                reports,
                views,
                POST,
                1,
                false,
                false,
                false,
                true,
                false,
                true,
                donut,
                1))
            service.add(Post( 1,
                3,
                1,
                1,
                1,
                "Текст поста!",
                2,
                1,
                true,
                comment,
                copyright,
                likes,
                reports,
                views,
                POST,
                1,
                false,
                false,
                false,
                true,
                false,
                true,
                donut,
                1))

            val update = Post(2,
                3,
                1,
                1,
                1,
                "Текст поста!",
                2,
                1,
                true,
                comment,
                copyright,
                likes,
                reports,
                views,
                POST,
                1,
                false,
                false,
                false,
                true,
                false,
                true,
                donut,
                1)

            val result = service.update(update)

            assertTrue(result)
        }

    @Test
    fun updateExisting_False() {
        service.add(Post( 1,
            3,
            1,
            1,
            1,
            "Текст поста!",
            2,
            1,
            true,
            comment,
            copyright,
            likes,
            reports,
            views,
            POST,
            1,
            false,
            false,
            false,
            true,
            false,
            true,
            donut,
            1))
        service.add(Post( 1,
            5,
            2,
            1,
            3,
            "Текст поста!",
            2,
            1,
            true,
            comment,
            copyright,
            likes,
            reports,
            views,
            POST,
            1,
            false,
            false,
            false,
            true,
            false,
            true,
            donut,
            1))
        service.add(Post( 1,
            3,
            1,
            1,
            1,
            "Текст поста!",
            2,
            1,
            true,
            comment,
            copyright,
            likes,
            reports,
            views,
            POST,
            1,
            false,
            false,
            false,
            true,
            false,
            true,
            donut,
            1))

        val update = Post(45,
            3,
            1,
            1,
            1,
            "Текст поста!",
            2,
            1,
            true,
            comment,
            copyright,
            likes,
            reports,
            views,
            POST,
            1,
            false,
            false,
            false,
            true,
            false,
            true,
            donut,
            1)

        val result = service.update(update)

        assertFalse(result)
    }


}
